/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EndpointmvcadapterApi
 */
public class EndpointmvcadapterApiTest {

    private final EndpointmvcadapterApi api = new EndpointmvcadapterApi();

    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGETTest() throws ApiException {
        // Object response = api.invokeUsingGET();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET1Test() throws ApiException {
        // Object response = api.invokeUsingGET1();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET10Test() throws ApiException {
        // Object response = api.invokeUsingGET10();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET11Test() throws ApiException {
        // Object response = api.invokeUsingGET11();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET12Test() throws ApiException {
        // Object response = api.invokeUsingGET12();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET13Test() throws ApiException {
        // Object response = api.invokeUsingGET13();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET2Test() throws ApiException {
        // Object response = api.invokeUsingGET2();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET3Test() throws ApiException {
        // Object response = api.invokeUsingGET3();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET4Test() throws ApiException {
        // Object response = api.invokeUsingGET4();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET5Test() throws ApiException {
        // Object response = api.invokeUsingGET5();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET6Test() throws ApiException {
        // Object response = api.invokeUsingGET6();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET7Test() throws ApiException {
        // Object response = api.invokeUsingGET7();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET8Test() throws ApiException {
        // Object response = api.invokeUsingGET8();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET9Test() throws ApiException {
        // Object response = api.invokeUsingGET9();

        // TODO: test validations
    }
    
}
