/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnvironmentmvcendpointApi
 */
public class EnvironmentmvcendpointApiTest {

    private final EnvironmentmvcendpointApi api = new EnvironmentmvcendpointApi();

    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET14Test() throws ApiException {
        // Object response = api.invokeUsingGET14();

        // TODO: test validations
    }
    
    /**
     * invoke
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invokeUsingGET15Test() throws ApiException {
        // Object response = api.invokeUsingGET15();

        // TODO: test validations
    }
    
    /**
     * value
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void valueUsingGETTest() throws ApiException {
        String name = null;
        // Object response = api.valueUsingGET(name);

        // TODO: test validations
    }
    
}
