/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.api;

import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.model.DateRange;
import io.swagger.client.model.User;
import junit.framework.Assert;

/**
 * API tests for HellocontrollerApi
 */
public class HellocontrollerApiTest
{

    private final HellocontrollerApi api = new HellocontrollerApi();

    /**
     * getUser
     *
     * 
     *
     * @throws ApiException
     *             if the Api call fails
     */
    @Test
    public void getUserUsingGETTest() throws ApiException
    {
	User response = api.getUserUsingGET();

	System.out.println(response);

	Assert.assertNotNull(response);
    }

    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *             if the Api call fails
     */
    @Test
    public void indexUsingGETTest() throws ApiException
    {
	String response = api.indexUsingGET();

	System.out.println(response);

	Assert.assertNotNull(response);
    }

    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *             if the Api call fails
     */
    @Test
    public void dateRangeUsingGETTest() throws ApiException
    {
	DateRange response = api.getDateUsingGET();

	System.out.println(response);

	Assert.assertNotNull(response);
    }

    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *             if the Api call fails
     */
    @Test
    public void postDateRange() throws ApiException
    {
	DateRange newDateRange = new DateRange();

	newDateRange.setFromDate("1999-01-01");
	newDateRange.setToDate("1999-12-12");


	System.out.println("before: " + newDateRange.toString());
	
	DateRange response = api.postDateUsingPOST(newDateRange);

	System.out.println("after: " + response);

	Assert.assertNotNull(response);
    }
}
